---
title: "Homework 11: Batch Processing"
author: "Aura M. Alonso-Rodríguez"
date: "April 8, 2020"
output: html_document
---

<br />
Full instructions for this homework are available [here](https://gotellilab.github.io/Bio381/Homeworks/Homework11_S2020.html). 


<br />

Repeat the exercise from the Batch Processing Lecture (7th April), but do it using real data sets rather than purely simulated. Check with folks in your lab to see if there are multiple data sets available for analysis. Stick to simple data analyses and graphics, but try to set it up as a batch process that will work on multiple files and save summary results to a common file.
If you can only find a data set, then simulate a couple of others by following the methods in Homework #6 by selecting appropriate statistical distributions and estimating parameters for those from the real data.

Hopefully, this exercise will contribute to some actual work that you are trying to do in your research!

```{r, warning=FALSE, message=FALSE}

# -------------------------------------------------------------------------------
# FUNCTION: reg_stats
# description: fits linear models, extract model stats
# inputs: 2-column data frame (x and y)
# outputs: slope, p-value, and r2
#################################################################################
reg_stats <- function(d = NULL) {
  if (is.null(d)) {
    x_var <- runif(10)
    y_var <- runif(10)
    d <- data.frame(x_var, y_var)
  }
  
  . <- lm(data=d, d[,3]~d[,2])
  . <- summary(.)
  stats_list <- list(Slope = round(.$coefficients[2,1], digits=8),
                     pVal = if (.$coefficients[2,4] <0.001) "< 0.001",
                     r2 = round(.$r.squared, digits=8))
  
return(stats_list)

} # end of reg_stats
# -------------------------------------------------------------------------------


# body of program ---------------------------------------------------------

library(TeachingDemos)
char2seed("beach day")

#################################################################################
# Global variables

file_folder <- "Hobo/"
n_files <- 24
file_out <- "StatsSummaryHobo.csv"
file_names <- list.files(path = file_folder)

# Create a data frame to hold summary file statistics

ID <- seq_along(file_names)
file_name <- file_names
slope <- rep(NA, length(file_names))
p_val <- rep(NA, length(file_names))
r2 <- rep(NA, length(file_names))

stats_out <- data.frame(ID, file_name, slope, p_val, r2)

#################################################################################
# batch process

for (i in seq_along(file_names)) {
  data <- read.table(file = paste(file_folder, file_names[i], sep = ""),
                     sep = ",", header = TRUE)
  d_clean <- data[complete.cases(data),]  # subset for clean cases (remove NAs)
  . <- reg_stats(d_clean)  # pull out regression stats from clean file
  stats_out[i,3:5] <- unlist(.)  # unlist, copy into last 3 columns
}
# set up an output file, incorporate time stamp and minimal metadata

write.table(cat("# Summary stats for ",
                "batch processing of regression models",
                "\n", "timestamp: ", as.character(Sys.time()),
                "\n", file = file_out, 
                row.names = "", col.names = "", sep = ""))

# now add the data frame
write.table(x = stats_out, file = file_out,
            row.names = FALSE, col.names = TRUE,
            sep = ",", append = TRUE)

print(stats_out)


```

