---
title: "Homework 4: Vectors"
author: "Aura M. Alonso-Rodríguez"
date: "February 5, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



<br />
Full instructions for this homework are available [here](https://gotellilab.github.io/Bio381/Homeworks/Homework04_S2020.html). 

<br />

##### Exercise 1  

###### Part a  
```{r}
z <- 1.1 ^ 2.2 ^ 3.3
print(z)
```

###### Part b  
```{r}
z <- (1.1 ^ 2.2) ^ 3.3
print(z)
```

###### Part c  
```{r}
z <- (3*1.1^3) + (2*1.1^2) + 1
print(z)
```

<br />

##### Exercise 2  

###### Part a  
```{r}
c(seq(from = 1, to = 8, by = 1),seq(from = 7, to = 1, by = -1))
```

###### Part b  
```{r}
c(1, rep(2,2), rep(3,3), rep(4,4), rep(5,5))

```

###### Part c  
```{r}
c(5, rep(4,2), rep(3,3), rep(2,4), rep(1,5))

```


<br />

##### Exercise 3  

```{r}
xy <- runif(2) 
print(xy) #cartesian coordinates

r <- sqrt((xy[1]^2)+(xy[2]^2))
th <- atan((xy[2])/(xy[1]))
c(r,th) #polar coordinates
```

<br />

##### Exercise 4  

```{r}
queue <- c("sheep", "fox", "owl", "ant")
print(queue)

a <- c(queue, "serpent") 
print(a)  # part a

b <- a[-1]
# a[!a %in% "sheep"] also works but not as simple
print(b)  # part b

c <- c("donkey", b)
print(c)  # part c

d <- c[-5]
print(d)  # part d

e <- d[-3]
print(e)  # part e

f <- append(e, "aphid", after = 2)
print(f) # part f

g <- which(f == "aphid")
print(g)  # part g

```

<br />

##### Exercise 5  

```{r}
v <- 1:100
v[!(!v%%2) + (!v%%3) + (!v%%7)]
```


